s2i

diff --git a/.s2i/bin/assemble b/.s2i/bin/assemble
--- a/.s2i/bin/assemble
+++ b/.s2i/bin/assemble
@@ -2,17 +2,17 @@
 echo "Custom scripts before assembling:"
 echo ""
 
-set +e
+#set +e
 
 [ $(id -u) -ne 0 ] && CHECK_OWNER=" -uid $(id -u)"
 
 # If argument does not exist, script will still exit with 0,
 # but at least we'll see something went wrong in the log
-if ! [ -e "$1" ] ; then
-  echo "ERROR: File or directory $1 does not exist." >&2
-  # We still want to end successfully
-  exit 0
-fi
+#if ! [ -e "$1" ] ; then
+#  echo "ERROR: File or directory $1 does not exist." >&2
+#  # We still want to end successfully
+#  exit 0#
+#fi
 
 find $SYMLINK_OPT "$1" ${CHECK_OWNER} \! -gid 0 -exec chgrp 0 {} +
 find $SYMLINK_OPT "$1" ${CHECK_OWNER} \! -perm -g+rw -exec chmod g+rw {} +
